http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
config.reload.automatic: true
config.reload.interval: 5s
pipeline.ordered: auto
queue.type: persisted
queue.max_bytes: 1gb